"""Paper pack — export LaTeX de experimentos para tese/artigo."""

from __future__ import annotations
from pathlib import Path
from typing import Any

EXPORT_DIR = Path(__file__).resolve().parent.parent / "experiments" / "exports"
EXPORT_DIR.mkdir(parents=True, exist_ok=True)


def latex_table(rows: list[dict[str, Any]], caption: str, label: str) -> str:
    if not rows:
        return f"% empty table {label}\n"
    keys = list(rows[0].keys())
    cols = "l" * len(keys)
    header = " & ".join(str(k).replace("_", "\\_") for k in keys) + " \\\\"
    body = []
    for r in rows[:40]:
        body.append(" & ".join(str(r.get(k, "")) for k in keys) + " \\\\")
    return "\n".join(
        [
            "\\begin{table}[ht]",
            "\\centering",
            f"\\caption{{{caption}}}",
            f"\\label{{{label}}}",
            f"\\begin{{tabular}}{{{cols}}}",
            "\\hline",
            header,
            "\\hline",
            *body,
            "\\hline",
            "\\end{tabular}",
            "\\end{table}",
            "",
        ]
    )


def build_paper_pack(experiments: list[dict[str, Any]], twin: dict, energy: dict, hil: dict, audit: dict) -> Path:
    parts = [
        "% Auto-generated by Ferrari IoT Postdoc Platform",
        "\\section{Resultados Experimentais — Ferrari IoT}",
        "",
        "\\subsection{Gêmeo digital e invariantes}",
        f"Modo atual: \\texttt{{{twin.get('mode', 'N/A')}}}.",
        "Invariantes:",
        "\\begin{itemize}",
    ]
    for inv in twin.get("invariants", []):
        parts.append(f"  \\item \\textbf{{{inv['id']}}}: {inv['rule']}")
    parts += ["\\end{itemize}", ""]

    parts += [
        "\\subsection{Modelo energético}",
        "Equações nominais:",
        "\\begin{align}",
        "P_{\\mathrm{motor}} &= P_0 + k_{\\mathrm{rpm}}\\cdot\\mathrm{rpm} \\\\",
        "P_{\\mathrm{total}} &= P_{\\mathrm{motor}}+P_{hl}+P_{sound}+P_{ac}+P_{track}+P_{spoiler} \\\\",
        "\\Delta E_{bat} &= -P_{\\mathrm{total}}\\Delta t \\\\",
        "\\Delta fuel &\\propto -P_{\\mathrm{motor}}\\Delta t",
        "\\end{align}",
        f"Potência instantânea: ${energy.get('power_w', 0)}\\,\\mathrm{{W}}$.",
        "",
        "\\subsection{Co-simulação HIL / QoS}",
        f"Delay={hil.get('delay_ms')} ms, loss={hil.get('loss_rate')}, "
        f"delivery={(hil.get('qos') or {}).get('delivery_ratio')}, "
        f"consistência={(hil.get('qos') or {}).get('consistency')}.",
        "",
        "\\subsection{Integridade (cadeia hash)}",
        f"Verificação: \\texttt{{{audit}}}.",
        "",
    ]

    for exp in experiments[-8:]:
        name = exp.get("name", "exp")
        eid = exp.get("experiment_id", "id")
        parts.append(f"\\subsection{{Experimento \\texttt{{{name}}} ({eid})}}")
        parts.append(f"Hipótese: {exp.get('hypothesis', '')}")
        metrics = exp.get("metrics") or {}
        parts.append(
            f"SQI={metrics.get('sync_quality_index')}, "
            f"amostras={metrics.get('sample_count')}, "
            f"tempo={metrics.get('wall_time_s')} s."
        )
        samples = exp.get("samples") or []
        if samples and isinstance(samples[0], dict):
            parts.append(latex_table(samples[:15], f"Amostras {name}", f"tab:{name}_{eid}"))
        parts.append("")

    # simple tikz placeholder for spectrum / latency figure
    parts += [
        "\\begin{figure}[ht]",
        "\\centering",
        "\\fbox{\\parbox{0.85\\linewidth}{\\centering Figura gerada no Research Lab (espectro Web Audio / latência HIL).}}",
        "\\caption{Painel experimental do Ferrari IoT Lab.}",
        "\\label{fig:ferrari-lab}",
        "\\end{figure}",
        "",
    ]

    out = EXPORT_DIR / "paper_pack.tex"
    out.write_text("\n".join(parts), encoding="utf-8")
    return out
